backend:
  name: github
  repo: mobilizehere/mobilizehere.com
  branch: master # Branch to update (master by default)

media_folder: "static/assets" # Folder where user uploaded files should go
public_folder: "/assets"
publish_mode: editorial_workflow

collections: # A list of collections the CMS should be able to edit
  - name: "podcast" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Podcast Episode" # Used in the UI, ie.: "New Post"
    folder: "src/pages/podcast" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields: # The fields each document in this collection have
      - {label: "Unique ID", name: "id", widget: "UniqueID", default: '', required: true}
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "podcast"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Artwork", name: "image", widget: "image", default: "/assets/mobilize_logo.jpg"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Is Episode", name: "isEpisode", widget: "isEpisode", default: true, required: false}
      - {label: "Media URL", name: "url", widget: "string"}
      - {label: "File Size (in bytes)", name: "length", widget: "number"}
      - {label: "Duration (mm:ss)", name: "duration", widget: "string"}
      - {label: "Explicit (yes/no)", name: "explicit", widget: "string", default: "no"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "resource"
    label: "Resources"
    folder: "src/data/resources"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Color", name: "color", widget: "string"}
      - {label: "Artwork", name: "image", widget: "image", default: "/assets/mobilize_logo.jpg"}
      - {label: "Link", name: "url", widget: "string"}
      - {label: "Description", name: "body", widget: "markdown", required: false}
  - name: "settings"
    label: "Settings"
    files:
      - name: "general"
        label: "General Info"
        file: "src/pages/info.md"
        description: "General Site Settings"
        fields:
          - {label: "Global title", name: "name", widget: "string"}
          - {label: "Contact Email", name: "email", widget: "string"}
          - {label: "Site Url", name: "website", widget: "string"}
          - {label: "Artwork", name: "image", widget: "image"}
          - {label: "iTunes Artwork (hosted on Amazon)", name: "itunesArtwork", widget: "string"}
          - {label: "itunes Summary", name: "itunesSummary", widget: "text"}
          - {label: "Mission Statement", name: "body", widget: "markdown"}
          - {label: "Contributors", name: "contributors", widget: "list"}


#backend:
#  name: git-gateway
#  branch: master
#
#media_folder: static/img
#public_folder: /img
#
#collections:
#  - name: "blog"
#    label: "Blog"
#    folder: "src/pages/blog"
#    create: true
#    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
#    fields:
#      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
#      - {label: "Title", name: "title", widget: "string"}
#      - {label: "Publish Date", name: "date", widget: "datetime"}
#      - {label: "Description", name: "description", widget: "text"}
#      - {label: "Body", name: "body", widget: "markdown"}
#      - {label: "Tags", name: "tags", widget: "list"}
#
#  - name: "pages"
#    label: "Pages"
#    files:
#      - file: "src/pages/about/index.md"
#        label: "About"
#        name: "about"
#        fields:
#          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page"}
#          - {label: "Title", name: "title", widget: "string"}
#          - {label: "Body", name: "body", widget: "markdown"}
#      - file: "src/pages/products/index.md"
#        label: "Products Page"
#        name: "products"
#        fields:
#          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "product-page"}
#          - {label: Title, name: title, widget: string}
#          - {label: Image, name: image, widget: image}
#          - {label: Heading, name: heading, widget: string}
#          - {label: Description, name: description, widget: string}
#          - {label: Intro, name: intro, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Blurbs, name: blurbs, widget: list, fields: [{label: Image, name: image, widget: image}, {label: Text, name: text, widget: text}]}]}
#          - {label: Main, name: main, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Image1, name: image1, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image2, name: image2, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image3, name: image3, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}]}
#          - {label: Testimonials, name: testimonials, widget: list, fields: [{label: Quote, name: quote, widget: string}, {label: Author, name: author, widget: string}]}
#          - {label: Full_image, name: full_image, widget: image}
#          - {label: Pricing, name: pricing, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: string}, {label: Plans, name: plans, widget: list, fields: [{label: Plan, name: plan, widget: string}, {label: Price, name: price, widget: string}, {label: Description, name: description, widget: string}, {label: Items, name: items, widget: list}]}]}
