backend:
  name: github
  repo: mobilizehere/mobilizehere.com
  branch: master # Branch to update (master by default)

media_folder: "static/assets" # Folder where user uploaded files should go
public_folder: "assets" #Not the public folder, rather where GraphQL will query images
publish_mode: editorial_workflow

collections: # A list of collections the CMS should be able to edit
  - name: "podcast" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Podcast Episode" # Used in the UI, ie.: "New Post"
    folder: "src/pages/podcast" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields: # The fields each document in this collection have
      - {label: "Legacy URL", name: "legacyURL", widget: "Legacy URL", default: '', required: false}
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "podcast"}
      - {label: "Title", name: "title", widget: "string", hint: "Do not include Mobilize or Episode Number in the title!!!"}
      - {label: "Artwork", name: "image", widget: "image", default: "/assets/mobilize_logo.jpg"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Episode Type", name: "episodeType", widget: "select", default: 'full', options: ['full', 'bonus', 'trailer']}
      - {label: "Episode Number", name: "episodeNumber", widget: "string", default: '', required: false, pattern: '/^[0-9]*$/g'}
      - {label: "Media URL", name: "url", widget: "string"}
      - {label: "File Size (in bytes)", name: "length", widget: "string", default: '', required: true, pattern: '/^[0-9]*$/g'}
      - {label: "Duration (mm:ss)", name: "duration", widget: "string"}
      - {label: "Explicit (yes/no)", name: "explicit", widget: "string", default: "no"}
      - {label: "Body", name: "body", widget: "markdown", required: false}
  - name: "resource"
    label: "Resources"
    folder: "src/data/resources"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Color", name: "color", widget: "string"}
      - {label: "Artwork", name: "image", widget: "image", default: "/assets/mobilize_logo.jpg"}
      - {label: "Link", name: "url", widget: "string"}
      - {label: "Description", name: "body", widget: "markdown", required: false}
  - name: "settings"
    label: "Settings"
    files:
      - name: "general"
        label: "General Info"
        file: "src/data/info/info.md"
        description: "General Site Settings"
        fields:
          - {label: "Global title", name: "name", widget: "string"}
          - {label: "Contact Email", name: "email", widget: "string"}
          - {label: "Site Url", name: "website", widget: "string"}
          - {label: "Artwork", name: "image", widget: "image"}
          - {label: "Keywords", name: "keywords", widget: "list"}
          - {label: "iTunes Artwork (hosted on Amazon)", name: "itunesArtwork", widget: "string"}
          - {label: "itunes Summary", name: "itunesSummary", widget: "text"}
          - {label: "Mission Statement", name: "body", widget: "markdown"}
          - {label: "Contributors", name: "contributors", widget: "contribList"}
