backend:
  name: github
  repo: mobilizehere/mobilizehere.com
  branch: master # Branch to update (master by default)

media_folder: "src/assets/static" # Folder where user uploaded files should go
public_folder: "/assets"
publish_mode: editorial_workflow

collections: # A list of collections the CMS should be able to edit
  - name: "podcast" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Podcast Episode" # Used in the UI, ie.: "New Post"
    folder: "site/content/podcast" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Unique ID", name: "id", widget: "UniqueID", default: '', required: true}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Artwork", name: "image", widget: "image", default: "/assets/mobilize_logo.jpg"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Is Episode", name: "isEpisode", widget: "isEpisode", default: true, required: false}
      - {label: "Media URL", name: "url", widget: "string"}
      - {label: "File Size (in bytes)", name: "length", widget: "number"}
      - {label: "Duration (mm:ss)", name: "duration", widget: "string"}
      - {label: "Explicit (yes/no)", name: "explicit", widget: "string", default: "no"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "resource"
    label: "Resource"
    folder: "site/content/resource"
    create: true
    fields: 
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Color", name: "color", widget: "string"}
      - {label: "Artwork", name: "image", widget: "image", default: "/assets/mobilize_logo.jpg"}
      - {label: "Link", name: "url", widget: "string"}
      - {label: "Description", name: "body", widget: "markdown", required: false}
  - name: "pages"
    label: "Pages"
    files:
      - name: "resources"
        label: "Resources (Take Action)"
        file: "site/content/resources/index.md"
        fields: 
          - {label: "TemplateKey", name: "templateKey", widget: "hidden", default: "resources"}
          - {label: "Title", name: "title", widget: "string"}
          - label: "Links"
            label_singular: "Link"
            name: "links"
            widget: "list"
            allow_add: true
            required: false
            fields: 
              - label: "Resource"
                name: "resource_object"
                widget: "object"
                fields: 
                  - {label: "Title", name: "title", widget: "string", default: "Resource"}
                  - {label: "URL", name: "url", widget: "string", default: "https://www.mobilizehere.com"}
#            fields: 
#              - {label: "Title", name: "title", widget: "string"}
#              - {label: "Color", name: "color", widget: "string"}
#              - {label: "Artwork", name: "image", widget: "image", default: "/assets/mobilize_logo.jpg"}
#              - {label: "Link", name: "url", widget: "string"}
  - name: "settings"
    label: "Settings"
    files:
      - name: "general"
        label: "General Info"
        file: "site/settings/info.md"
        description: "General Site Settings"
        fields:
          - {label: "Global title", name: "name", widget: "string"}
          - {label: "Contact Email", name: "email", widget: "string"}
          - {label: "Site Url", name: "website", widget: "string"}
          - {label: "Artwork", name: "image", widget: "image"}
          - {label: "iTunes Artwork (hosted on Amazon)", name: "itunesArtwork", widget: "string"}
          - {label: "Mission Statement", name: "body", widget: "markdown"}
          - {label: "Contributors", name: "contributors", widget: "list"}